name: Release Workflow
run-name: Release Artifact Build Workflow for ${{ github.event.release.tag_name }}
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    name: Build Artifacts

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup python 
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install Tkinter system dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-tk

      - name: Install Project Dependencies
        run: |
          pip install . 
      
      - name: Install Nuitka standalone dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y patchelf

      - name: Build Tkinter executable
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: main.py
          mode: onefile
          enable-plugins: tk-inter

      - name: Build PySide6 executable
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: main_qt.py
          mode: onefile
          enable-plugins: pyside6

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }} Build
          path: |
            build/*.exe
            build/*.bin
            build/*.app/**/*
          include-hidden-files: true
